"""add_chat_tables

Revision ID: 1212b95c3024
Revises: b5c6d7e8f9a0
Create Date: 2026-05-24 20:29:46.073413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1212b95c3024'
down_revision: Union[str, None] = 'b5c6d7e8f9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_user_id', sa.UUID(), nullable=False),
    sa.Column('specialist_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialist_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_user_id', 'specialist_user_id', name='uq_conversations_pair')
    )
    op.create_index(op.f('ix_conversations_patient_user_id'), 'conversations', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_specialist_user_id'), 'conversations', ['specialist_user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('message_kind', sa.Enum('TEXT', 'SYSTEM_RED_FLAG', name='messagekind'), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_is_read', 'messages', ['conversation_id', 'is_read'], unique=False)
    op.create_index('ix_messages_conversation_sent_at', 'messages', ['conversation_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_sent_at', table_name='messages')
    op.drop_index('ix_messages_conversation_is_read', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_specialist_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_patient_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
