"""add_user_plan_archives_table

Revision ID: 6863abb0ea9a
Revises: c1d2e3f4a5b6
Create Date: 2026-06-06 19:11:56.280468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6863abb0ea9a'
down_revision: Union[str, None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_plan_archives',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'message_id')
    )
    op.create_index('ix_user_plan_archives_message_id', 'user_plan_archives', ['message_id'], unique=False)
    op.create_index('ix_user_plan_archives_user_id', 'user_plan_archives', ['user_id'], unique=False)
    op.drop_index('uq_active_relation', table_name='patient_specialist_relations', postgresql_where="(status = ANY (ARRAY['PENDING'::relationstatus, 'APPROVED'::relationstatus]))")
    op.drop_index('ix_specialist_certifications_profile_id', table_name='specialist_certifications')
    op.create_index(op.f('ix_specialist_certifications_specialist_profile_id'), 'specialist_certifications', ['specialist_profile_id'], unique=False)
    op.drop_index('ix_specialist_education_profile_id', table_name='specialist_education')
    op.create_index(op.f('ix_specialist_education_specialist_profile_id'), 'specialist_education', ['specialist_profile_id'], unique=False)
    op.drop_index('ix_specialist_work_experience_profile_id', table_name='specialist_work_experience')
    op.create_index(op.f('ix_specialist_work_experience_specialist_profile_id'), 'specialist_work_experience', ['specialist_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specialist_work_experience_specialist_profile_id'), table_name='specialist_work_experience')
    op.create_index('ix_specialist_work_experience_profile_id', 'specialist_work_experience', ['specialist_profile_id'], unique=False)
    op.drop_index(op.f('ix_specialist_education_specialist_profile_id'), table_name='specialist_education')
    op.create_index('ix_specialist_education_profile_id', 'specialist_education', ['specialist_profile_id'], unique=False)
    op.drop_index(op.f('ix_specialist_certifications_specialist_profile_id'), table_name='specialist_certifications')
    op.create_index('ix_specialist_certifications_profile_id', 'specialist_certifications', ['specialist_profile_id'], unique=False)
    op.create_index('uq_active_relation', 'patient_specialist_relations', ['patient_id', 'specialist_id'], unique=False, postgresql_where="(status = ANY (ARRAY['PENDING'::relationstatus, 'APPROVED'::relationstatus]))")
    op.drop_index('ix_user_plan_archives_user_id', table_name='user_plan_archives')
    op.drop_index('ix_user_plan_archives_message_id', table_name='user_plan_archives')
    op.drop_table('user_plan_archives')
    # ### end Alembic commands ###
